name = "class-schedule-builder"
main = "src/server.ts"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "class_schedule_builder_db"
database_id = "529cb5fe-da6b-4a22-8d3c-1548b78df605"
migrations_dir = "lib/prisma/migrations"
